# Configuration par défaut pour le projet haze-removal

algorithm:
  patch_size: 15 # Taille du patch (doit être impair)
  omega: 0.95 # Contrôle la quantité de brume à enlever
  atmospheric_light_percentile: 0.001 # 0.1% des pixels les plus brillants
  t0: 0.1 # Empêche la transmission d'être trop faible

guided_filter:
  radius: 60 # Rayon du filtre guidé (plus il est grand, plus le lissage est fort)
  epsilon: 1.0e-3 # Paramètre de régularisation (petite valeur pour éviter de trop lisser les contours)

logging:
  level: "INFO"